kubeVersion: 1.32.2

repositories:
  # https://istio.io/latest/docs/setup/install/helm/#prerequisites
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  # Install Gateway API CRDs
  # https://gateway-api.sigs.k8s.io/guides/#install-standard-channel
  - name: gateway-api
    chart: ./kustomize/gateway-api
    namespace: default

  # Install Istio (sidecar mode)
  # https://istio.io/latest/docs/setup/install/helm/
  - name: istio-base
    chart: istio/base
    version: 1.28.0
    namespace: istio-system
  - name: istiod
    chart: istio/istiod
    version: 1.28.0
    namespace: istio-system
    wait: true
  # Install Istio Ingress Gateway
  # NOTE: Use kustomize to install istio-ingressgateway as NodePort and specify its port.
  # https://istio.io/latest/docs/setup/additional-setup/gateway/
  - name: istio-ingressgateway
    chart: ./kustomize/istio-ingressgateway
    namespace: istio-system
    wait: true
    # NOTE: Required Gateway API CRDs since this manifest includes Gateway resource.
    needs:
      - default/gateway-api
  # Install Istio integrations
  # https://istio.io/latest/docs/ops/integrations/
  - name: istio-integrations
    chart: ./kustomize/istio-integrations
    namespace: istio-system
    needs:
      - istio-system/istio-ingressgateway
