kubeVersion: 1.32.2

repositories:
  # https://istio.io/latest/docs/setup/install/helm/#prerequisites
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: gateway-api
    chart: ./kustomize/gateway-api
    namespace: ngf

  - needs:
      - ngf/gateway-api
    name: ngf
    # https://docs.nginx.com/nginx-gateway-fabric/get-started/#install-the-helm-chart
    chart: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    version: 2.2.1
    namespace: ngf
    values:
      - values/ngf/values.yaml
    # Required when CRDs are included in the chart.
    # https://helmfile.readthedocs.io/en/latest/#configuration
    disableValidationOnInstall: true

  - needs:
      - ngf/ngf
    name: ngf-gateway
    chart: ./kustomize/ngf-gateway
    namespace: ngf-gateway

  - needs:
      - ngf-gateway/ngf-gateway
    name: istio-base
    chart: istio/base
    version: 1.28.0
    namespace: istio-system

  - needs:
      - istio-system/istio-base
    name: istiod
    chart: istio/istiod
    version: 1.28.0
    namespace: istio-system
    wait: true

  - needs:
      - istio-system/istiod
    name: istio-sample-app
    chart: ./kustomize/istio-sample-app
    wait: true
